id: P000682
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2390
  title: སྡེབ་སྦྱོར་གྱི་རྣམ་བཤད་ཤེས་བྱ་ཀུན་རིག་མཁྱེན་གཏེར་ལྷ་ཡི་འཛུམ་ཟེར
  author: ''
  volumes:
    849b600692eb4394a3ccc9ae4928a906:
      image_group_id: I1CZ2444
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
