id: IF851CE56
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T15:59:52+00:00'
last_modified: '2022-06-07T12:39:06.699035+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2390
  title: སྡེབ་སྦྱོར་གྱི་རྣམ་བཤད་ཤེས་བྱ་ཀུན་རིག་མཁྱེན་གཏེར་ལྷ་ཡི་འཛུམ་ཟེར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    0B7F:
      image_group_id: I1CZ2444
      title: ''
      total_pages: 324
      order: 1
      base_file: 0B7F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
